In [1]:
import numpy as np
import matplotlib.pyplot as plt
import time
import pandas as pd
import sys

import torch
import torch.nn as nn

from torchmetrics import MeanAbsolutePercentageError

from data.passenger import get_passenger_data
from data.gold import get_gold_data

In [2]:
n = np.linspace(0,10,5)
n

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [3]:
t = torch.linspace(0,10,5)
t

tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])

In [4]:
gold_data = get_gold_data()
passenger_data = get_passenger_data()

In [6]:
#gold_data.head()
passenger_data.head(2)

Date  Passengers
0  1949-01         112
1  1949-02         118

In [7]:
# creating tensor from targets_df 
passenger_tensor = torch.tensor(passenger_data['Passengers'].values)

# printing out result
print(passenger_tensor)

tensor([112, 118, 132, 129, 121, 135, 148, 148, 136, 119, 104, 118, 115, 126,
        141, 135, 125, 149, 170, 170, 158, 133, 114, 140, 145, 150, 178, 163,
        172, 178, 199, 199, 184, 162, 146, 166, 171, 180, 193, 181, 183, 218,
        230, 242, 209, 191, 172, 194, 196, 196, 236, 235, 229, 243, 264, 272,
        237, 211, 180, 201, 204, 188, 235, 227, 234, 264, 302, 293, 259, 229,
        203, 229, 242, 233, 267, 269, 270, 315, 364, 347, 312, 274, 237, 278,
        284, 277, 317, 313, 318, 374, 413, 405, 355, 306, 271, 306, 315, 301,
        356, 348, 355, 422, 465, 467, 404, 347, 305, 336, 340, 318, 362, 348,
        363, 435, 491, 505, 404, 359, 310, 337, 360, 342, 406, 396, 420, 472,
        548, 559, 463, 407, 362, 405, 417, 391, 419, 461, 472, 535, 622, 606,
        508, 461, 390, 432])
